version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3219035
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3219035
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A config worker --loglevel=info  # Замените 'your_project_name' на имя вашего проекта
    depends_on:
      - db
      - redis
